title: Jeff Mesnil
author :
  name : Jeff Mesnil
  email : jmesnil@gmail.com
  github : jmesnil
  twitter : jmesnil

interpolate: true
img_base_url: https://media.jmesnil.net/
# replace by / to test with local assets
#assets_url: /
assets_url: https://media.jmesnil.net/

atom_base_url: http://jmesnil.net

minify: true

profiles:
  staging:
    deploy:
      type: s3
      bucket: s3://staging.jmesnil.net/
  production:
    deploy:
      type: s3
      bucket: s3://www.jmesnil.net/

generation:
  in_threads: 2
