title: Jeff Mesnil
author :
  name : Jeff Mesnil
  email : jmesnil@gmail.com
  github : jmesnil
  twitter : jmesnil

img_base_url: http://media.jmesnil.net/
# replace by / to test with local assets
assets_url: http://media.jmesnil.net/

base_url: http://jmesnil.net/

google_analytics: UA-257783-1

profiles:
  staging:
    deploy:
      type: s3
      bucket: s3://staging.jmesnil.net/
  production:
    deploy:
      type: s3
      bucket: s3://jmesnil.net/